import type { TideForecast, TidePoint, TideStation } from "../types/tides";
import { isoUtc } from "../utils/format";

const API = "https://api-iwls.dfo-mpo.gc.ca/api/v1";
function stringValue(record: Record<string, unknown>, keys: string[]): string | undefined { for (const key of keys) { const value = record[key]; if (typeof value === "string" && value.trim()) return value; } }
function numberValue(record: Record<string, unknown>, keys: string[]): number | undefined { for (const key of keys) { const value = Number(record[key]); if (Number.isFinite(value)) return value; } }
function normalizeStation(raw: unknown): TideStation | null { if (!raw || typeof raw !== "object") return null; const record = raw as Record<string, unknown>; const id = stringValue(record, ["id", "stationId", "_id"]); const name = stringValue(record, ["officialName", "name", "stationName"]); if (!id || !name) return null; return { id, name, code: stringValue(record, ["code", "stationCode"]), latitude: numberValue(record, ["latitude", "lat"]), longitude: numberValue(record, ["longitude", "lon", "lng"]) }; }
function normalizePoint(raw: unknown, type?: TidePoint["type"]): TidePoint | null { if (!raw || typeof raw !== "object") return null; const record = raw as Record<string, unknown>; const time = stringValue(record, ["eventDate", "time", "date"]); const height = numberValue(record, ["value", "height", "waterLevel"]); if (!time || height === undefined) return null; const eventTypeRaw = stringValue(record, ["event", "type", "eventType"])?.toLowerCase(); const eventType = eventTypeRaw?.includes("high") ? "high" : eventTypeRaw?.includes("low") ? "low" : type; return { time, height, type: eventType }; }
async function fetchJson(url: string): Promise<unknown> { const response = await fetch(url); if (!response.ok) throw new Error(`Tide request failed (${response.status})`); return response.json(); }
export async function findTideStation(searchName: string, latitude: number, longitude: number): Promise<TideStation> { const raw = await fetchJson(`${API}/stations`); const records = Array.isArray(raw) ? raw : ((raw as Record<string, unknown>)?.stations as unknown[]) ?? []; const stations = records.map(normalizeStation).filter((station): station is TideStation => station !== null); const words = searchName.toLowerCase().split(/\s+/); const named = stations.filter((station) => words.every((word) => station.name.toLowerCase().includes(word))); const candidates = named.length ? named : stations; if (!candidates.length) throw new Error("No Canadian tide stations were returned."); return [...candidates].sort((a, b) => { const distance = (station: TideStation) => station.latitude === undefined || station.longitude === undefined ? Number.POSITIVE_INFINITY : Math.hypot(station.latitude - latitude, station.longitude - longitude); return distance(a) - distance(b); })[0]; }
async function fetchSeries(stationId: string, code: string, from: Date, to: Date): Promise<TidePoint[]> { const params = new URLSearchParams({ "time-series-code": code, from: isoUtc(from), to: isoUtc(to) }); const raw = await fetchJson(`${API}/stations/${encodeURIComponent(stationId)}/data?${params}`); const records = Array.isArray(raw) ? raw : ((raw as Record<string, unknown>)?.data as unknown[]) ?? []; return records.map((item) => normalizePoint(item, code === "wlp-hilo" ? undefined : "prediction")).filter((point): point is TidePoint => point !== null); }
function classifyHighLowEvents(points: TidePoint[]): TidePoint[] { const sorted = [...points].sort((a, b) => Date.parse(a.time) - Date.parse(b.time)).filter((point, index, all) => index === 0 || point.time !== all[index - 1].time); if (sorted.length < 2) return sorted; const firstType: TidePoint["type"] = sorted[0].height > sorted[1].height ? "high" : "low"; return sorted.map((point, index) => ({ ...point, type: index % 2 === 0 ? firstType : firstType === "high" ? "low" : "high" })); }
async function fetchInSevenDayChunks(stationId: string, code: string, from: Date, days: number) { const requests: Promise<TidePoint[]>[] = []; for (let offset = 0; offset < days; offset += 7) { const chunkFrom = new Date(from); chunkFrom.setDate(chunkFrom.getDate() + offset); const chunkTo = new Date(from); chunkTo.setDate(chunkTo.getDate() + Math.min(offset + 7, days)); requests.push(fetchSeries(stationId, code, chunkFrom, chunkTo)); } const points = (await Promise.all(requests)).flat(); return code === "wlp-hilo" ? classifyHighLowEvents(points) : points.filter((point, index, all) => all.findIndex((other) => other.time === point.time && other.type === point.type) === index); }
export async function fetchTides(searchName: string, latitude: number, longitude: number): Promise<TideForecast> { const station = await findTideStation(searchName, latitude, longitude); const from = new Date(); from.setHours(from.getHours() - 3); const chartTo = new Date(from); chartTo.setHours(chartTo.getHours() + 75); const [pointsResult, eventsResult] = await Promise.allSettled([fetchSeries(station.id, "wlp", from, chartTo), fetchInSevenDayChunks(station.id, "wlp-hilo", from, 15)]); const points = pointsResult.status === "fulfilled" ? pointsResult.value : []; const events = eventsResult.status === "fulfilled" ? eventsResult.value : []; if (!points.length && !events.length) throw new Error("The station was found, but no prediction series was available."); return { station, points: points.length ? points : events.slice(0, 16), events }; }
